### PR TITLE
[Feature] Changing plan confirmation window

### LINKED ISSUE #444: Integrate Confirmation window to the payment dialog
As user I whant to see a Confirmation when I click to "Change plan" button

### PR DESCRIPTION
**Pull request by ilyamore88**
Closes #444

### CODE REVIEW

**Review by nikmel2803 — APPROVED** [review]

**Comment by neSpecc** [comment]
Why we need to confirm changing from Free to Paid plan? I think, in this case, user will see a Payment Dialog and he'll allow dismiss it.

image

**Comment by neSpecc** [comment]
I'm on paid plan, and I'm clicking on Change to Free. I see wrong text (about payment)

image

**Comment by neSpecc** [comment]
Clicking on Confirm, but nothing happened. Just closes a confirmation.

**Comment by ilyamore88** [comment]
> Clicking on Confirm, but nothing happened. Just closes a confirmation.

Can't reproduce.

**Comment by neSpecc** [comment]
> > Clicking on Confirm, but nothing happened. Just closes a confirmation.
> 
> Can't reproduce.

1. Select project with paid plan
2. Change to free
3. Try to change to paid again — nothing happened

**Comment by ilyamore88** [comment]
@neSpecc, I can't reproduce your bug. Can you test my request again and send more info about the bug: error message, stack trace, etc.

**Comment by ilyamore88** [comment]
@neSpecc's bug is reproduced without this request. I described this problem in issues #458 and #459.
For changing a workspace plan, you should refresh the page after changing. A new current plan will be displayed on the Billing information page.
There will be no need to refresh the page after payment if the current plan is automatically renewed.

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
