### PR TITLE
[Feature] Display invite link with hash

### PR DESCRIPTION
**Pull request by ilyamore88**
Displays invite link to workspace with invite hash.
image

### CODE REVIEW

**Review by neSpecc — CHANGES_REQUESTED** [review]
1. Open stage main page
2. Got to some workspace
3. Go to Workspace settings / Team
4. There will be `https://stage.hawk.so/join/undefined`

image

And also the `Copy` button has incorrect paddings and alignment.

**Comment by ilyamore88** [comment]
> And also the `Copy` button has incorrect paddings and alignment.

Fixed:
image
image

**Comment by ilyamore88** [comment]
> There will be `https://stage.hawk.so/join/undefined`

Fixed. I added `inviteHash` to the query for all workspaces and projects.

**Review by nikmel2803 — CHANGES_REQUESTED** [review]
image

**Review by nikmel2803 — APPROVED** [review]

**Review by talyguryn — APPROVED** [review]

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
